channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - librosa
  - pysoundfile
  - scipy
  - praatio
  - pytest
  - reaper
  - setuptools_scm
  - pip:
      - build
      - twine
      - pyraat
